### ISSUE TITLE
http://www.pm.inf.ethz.ch/people/dasenov broken link

### ISSUE THREAD

**Issue by 0joshuaolson1** [dimitar-asenov/Envision#284]
All instances should be updated, but I don't know what to.

**Comment by dimitar-asenov** [comment]
Thanks for reporting this. I just updated all the broken links (I hope). Let me know if you stumble upon another one.

If you have any other comments or questions about Envision, don't hesitate to ask. I know the current state can be a bit rough so I'm here to help. :)
