### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Vm900** [dimitar-asenov/Envision#441]
Hi,
I have been trying to compile envision.I keep getting this error -->>
CMake Error at /home/vmur/Qt5.11.2/5.11.2/gcc_64/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5WebKitWidgets"
  with any of the following names:

    Qt5WebKitWidgetsConfig.cmake
    qt5webkitwidgets-config.cmake

  Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebKitWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  VisualizationBase/CMakeLists.txt:268 (find_package)

-----------------------------------------------------------------------------------------------------------------------------
I do have the qt sources installed on my system plus Qt5WebKitWidgets.
Can you help me out please.
Thanks

**Comment by Vm900** [comment]
Solved it by adding the Qt5WebKitWidgets_DIR but another cropped up.Cannot find boost libraries,but i have them installed.Help Thanks

**Comment by dimitar-asenov** [comment]
Hi and thanks for your interest in Envision.

I'm glad you eventually resolved your first issue. I'm not sure why you need this additional configuration for QtWebKit. Perhaps your distro doesn't setup the paths the way Ubuntu does. 

I just tried today on Ubuntu 18.10. After a minor boost-python related fix (which I just pushed to dev) everything worked smoothly following [these instructions](http://dimitar-asenov.github.io/Envision/compilation.html).

You should try syncing to the latest commit. Perhaps it will resolve your boost issue. Otherwise, please post the full CMAKE error output and I could have a look. Please also tell me what Linux distro you are using.

**Comment by Vm900** [comment]
Hi,
I am on ubuntu budgie with ubuntu 18.04.02
I think i'm having to make all this extra configs coz of the way i installed
Qt.I had to use the offline installer since apt could not find qt-sdk.However i've synced everything but stii getting the same error:

Configuring Plugin: CppExport 
Using precompiled header for CppExport 
Plugin CppExport contains key bindings
CMake Error at CppImport/CMakeLists.txt:14 (string):
  string begin index: 2 is out of range 0 - 0


Configuring Plugin: CppImport 
Using precompiled header for CppImport 
CMake Error at PythonWrapperGenerator/CMakeLists.txt:14 (string):
  string begin index: 2 is out of range 0 - 0


Using precompiled header for PythonWrapperGenerator 
Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.7", minimum required is "3") 
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1626 (message):
  No header defined for python-py35; skipping header check
Call Stack (most recent call first):
  InformationScripting/CMakeLists.txt:12 (find_package)


CMake Error at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1947 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.65.1

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_python-py35

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  InformationScripting/CMakeLists.txt:12 (find_package)


Configuring Plugin: InformationScripting 
Using precompiled header for InformationScripting 
Plugin InformationScripting contains styles
Plugin InformationScripting contains scripts
Configuring Plugin: ContractsLibrary 
Using precompiled header for ContractsLibrary 
Plugin ContractsLibrary contains styles
Configuring Plugin: Alloy 
Using precompiled header for Alloy 
Configuring Plugin: CustomMethodCall 
Using precompiled header for CustomMethodCall 
Plugin CustomMethodCall contains styles
Configuring Plugin: ControlFlowVisualization 
Using precompiled header for ControlFlowVisualization 
Plugin ControlFlowVisualization contains styles
Configuring incomplete, errors occurred!
See also "/tmp/QtCreator-VlUErc/qtc-cmake-HQLRLbqk/CMakeFiles/CMakeOutput.log".
CMake Project parsing failed.

**Comment by Vm900** [comment]
I 've heard a response from one of the people at boost.org.Here was his response:
Sorry, I'm not maintaining any CMake logic to build third-party software with Boost.Python. (In fact, Boost.Python itself isn't built with CMake either.)
I'd suspect that the issue is related to the naming of the library: We have recently started to include the Python version into the library name itself, so with more recent Boost versions you would use e.g. -lboost_python36, etc. It's possible that the CMake logic hasn't caught up to these changes yet.
But again, I'm not involved in this infrastructure, so this is just a guess.
---------------------------------------------------------------------------------------------------------------------------------------------------------
I don't know if this will clear things up a bit.
Thanks

**Comment by dimitar-asenov** [comment]
Try changing line 9 of InformationScripting/CMakeLists.txt from

`
find_package(Boost REQUIRED python3)`

to 

`find_package(Boost REQUIRED python-py36)`

**Comment by Vm900** [comment]
Hello,
Changed the line now i'm getting -
Plugin CppExport contains key bindings
CMake Error at CppImport/CMakeLists.txt:14 (string):
  string begin index: 2 is out of range 0 - 0


Configuring Plugin: CppImport 
Using precompiled header for CppImport 
CMake Error at PythonWrapperGenerator/CMakeLists.txt:14 (string):
  string begin index: 2 is out of range 0 - 0


Using precompiled header for PythonWrapperGenerator 
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1626 (message):
  No header defined for python-py36; skipping header check
Call Stack (most recent call first):
  InformationScripting/CMakeLists.txt:12 (find_package)


Boost version: 1.65.1
Found the following Boost libraries:
  python-py36
Configuring Plugin: InformationScripting 
Using precompiled header for InformationScripting 
Plugin InformationScripting contains styles
Plugin InformationScripting contains scripts
Configuring Plugin: ContractsLibrary 
Using precompiled header for ContractsLibrary 
Plugin ContractsLibrary contains styles
Configuring Plugin: Alloy 
Using precompiled header for Alloy 
Configuring Plugin: CustomMethodCall 
Using precompiled header for CustomMethodCall 
Plugin CustomMethodCall contains styles
Configuring Plugin: ControlFlowVisualization 
Using precompiled header for ControlFlowVisualization 
Plugin ControlFlowVisualization contains styles
Configuring incomplete, errors occurred!
See also "/tmp/QtCreator-pIIYeG/qtc-cmake-MQKySktZ/CMakeFiles/CMakeOutput.log".
CMake Project parsing failed.

**Comment by dimitar-asenov** [comment]
Oh, this was my mistake, sorry. After a recent change the project requires LLVM 7, but I forgot to update the compilation instructions accordingly. I just pushed the [new instructions](http://dimitar-asenov.github.io/Envision/compilation.html) detailing what llvm-7 packages you need.

Your error suggests that your LLVM version is not correct or LLVM is not installed. After installing llvm-7, if you run `envision/misc/llvm-config-envision.sh --ldflags` manually in the terminal, you should see something like: `-L/usr/lib/llvm-7/lib`

Please let me know if this fixes your issue. I would really like to make it easy for others to experiment with Envision.

**Comment by Vm900** [comment]
Almost there.Installed llvm-7 and i was cooking until this ->
[ 26%] Building CXX object InteractionBase/CMakeFiles/InteractionBase.dir/src/commands/COpenDir.cpp.o
/home/vmur/Envision/InteractionBase/src/commands/COpenDir.cpp:52:31: error: extra ‘;’ [-Wpedantic]
 COpenDir::Parser::~Parser() {}; // Emit vtable here.
                               ^
InteractionBase/CMakeFiles/InteractionBase.dir/build.make:2246: recipe for target 'InteractionBase/CMakeFiles/InteractionBase.dir/src/commands/COpenDir.cpp.o' failed
CMakeFiles/Makefile2:1554: recipe for target 'InteractionBase/CMakeFiles/InteractionBase.dir/all' failed
Makefile:129: recipe for target 'all' failed
make[2]: *** [InteractionBase/CMakeFiles/InteractionBase.dir/src/commands/COpenDir.cpp.o] Error 1
make[1]: *** [InteractionBase/CMakeFiles/InteractionBase.dir/all] Error 2
make: *** [all] Error 2
00:32:38: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project Project (kit: Desktop Qt 5.11.2 GCC 64bit)
When executing step "CMake Build"
00:32:38: Elapsed time: 01:15.
-------------------------------------------------------------------------------------------------------------------------------
I must apologize this is my first time working in Qtcreator

**Comment by dimitar-asenov** [comment]
Thanks. I see that you're compiling with GCC which caught some extra errors compared to clang, which I use recently.

I just compiled everything with GCC and fixed all errors that it reported. I pushed the corresponding commit.

Hopefully things should work OK for you now. Once everything compiles here are some ideas for [trying Envision](http://dimitar-asenov.github.io/Envision/try_envision.html). As Envision is only a research prototype, there is much to be desired in the area of project management/opening/closing files. Do let me know if you encounter difficulties.

**Comment by Vm900** [comment]
Hi,
Failed to compile again,however this time it got to 71% unlike the initial 26%.I got this now-->>
[ 71%] Built target OODebug_autogen
[ 71%] Building CXX object OODebug/CMakeFiles/OODebug.dir/OODebug_autogen/mocs_compilation.cpp.o
In file included from /home/vmur/Envision/DebugBuild/OODebug/OODebug_autogen/mocs_compilation.cpp:2:0:
/home/vmur/Envision/DebugBuild/OODebug/OODebug_autogen/UVLADIE3JM/moc_OODebugPlugin.cpp:66:1: error: ‘QT_INIT_METAOBJECT’ does not name a type; did you mean ‘Q_INIT_RESOURCE’?
 QT_INIT_METAOBJECT const QMetaObject OODebug::OODebugPlugin::staticMetaObject = {
 ^~~~~~~~~~~~~~~~~~
 Q_INIT_RESOURCE
/home/vmur/Envision/DebugBuild/OODebug/OODebug_autogen/UVLADIE3JM/moc_OODebugPlugin.cpp:69:2: error: extra ‘;’ [-Wpedantic]
 };
  ^
In file included from /home/vmur/Envision/DebugBuild/OODebug/OODebug_autogen/mocs_compilation.cpp:3:0:
/home/vmur/Envision/DebugBuild/OODebug/OODebug_autogen/7IHDDUGULJ/moc_DebugConnector.cpp:65:1: error: ‘QT_INIT_METAOBJECT’ does not name a type; did you mean ‘Q_INIT_RESOURCE’?
 QT_INIT_METAOBJECT const QMetaObject OODebug::DebugConnector::staticMetaObject = {
 ^~~~~~~~~~~~~~~~~~
 Q_INIT_RESOURCE
/home/vmur/Envision/DebugBuild/OODebug/OODebug_autogen/7IHDDUGULJ/moc_DebugConnector.cpp:68:2: error: extra ‘;’ [-Wpedantic]
 };
  ^
OODebug/CMakeFiles/OODebug.dir/build.make:926: recipe for target 'OODebug/CMakeFiles/OODebug.dir/OODebug_autogen/mocs_compilation.cpp.o' failed
make[2]: *** [OODebug/CMakeFiles/OODebug.dir/OODebug_autogen/mocs_compilation.cpp.o] Error 1
CMakeFiles/Makefile2:3021: recipe for target 'OODebug/CMakeFiles/OODebug.dir/all' failed
Makefile:129: recipe for target 'all' failed
make[1]: *** [OODebug/CMakeFiles/OODebug.dir/all] Error 2
make: *** [all] Error 2
13:40:39: The process "/usr/bin/cmake" exited with code 2.
Error while building/deploying project Project (kit: Desktop Qt 5.11.2 GCC 64bit)
When executing step "CMake Build"

**Comment by dimitar-asenov** [comment]
This is an error in the files that qmake automatically generates during compilation, it probably has to do with your combination of Qt version and compiler. I'm not getting this, even with GCC.

What is your GCC and Qt version?

Since this is essentially just a warning (turned into error by a flag) it's safe to disable it. Try removing `-pedantic-errors` and/or `-Werror` from line 41 of envision/CMake/common.cmake

**Comment by Vm900** [comment]
I have gcc 7.3.0 and Qt 5.11.2 However,i've noticed the common.cmake  file is empty.I don't know if that's going to be another problem.

**Comment by dimitar-asenov** [comment]
Those versions of Qt and Gcc should work fine.

Nothing would have worked if the `common.cmake` file was empty. Did you perhaps make a typo when opening it, causing your editor to create a new empty file?

I'm talking about [this file](https://github.com/dimitar-asenov/Envision/blob/development/CMake/common.cmake).

**Comment by Vm900** [comment]
I don't want to give up yet.Yes,you were right about the typo.But problems persist.

CMake Warning at VisualizationBase/CMakeLists.txt:6 (add_library):
  Cannot generate a safe runtime search path for target VisualizationBase
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libQt5Network.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/vmur/Qt5.11.2/5.11.2/gcc_64/lib

  Some of these libraries may not be found correctly.


CMake Warning at OODebug/CMakeLists.txt:6 (add_library):
  Cannot generate a safe runtime search path for target OODebug because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libQt5Network.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/vmur/Qt5.11.2/5.11.2/gcc_64/lib

  Some of these libraries may not be found correctly.

**Comment by Vm900** [comment]
Finally compiled.All i did was switch kits and voila!.I got a new toy now.Thank you for your patience and help

**Comment by dimitar-asenov** [comment]
Great, I'm glad it worked out in the end. I hope you will have a good time playing around. If you run into any issue do let me know. I'd also be curious to know how you came across Envision and what your experience with it is.

Cheers.
