### ISSUE TITLE
Parser can't parse expression when changing the size of a new array expression

### ISSUE THREAD

**Issue by lukedirtwalker** [dimitar-asenov/Envision#83]
I have simple program where I have the following line:
int[] foo=new int[10]
when I now edit the 10, e.g. delete the zero the parser fails to parse it correctly.
The tokenizer generates the following tokens:
int, [], foo, =, new, int, [, 1, ]
if you tell me where to look, I will try to fix it.

**Comment by dimitar-asenov** [comment]
Thanks for this bug Lukas. As I'm currently changing this stuff and it's quite tricky I'll look into it myself.
